### ISSUE TITLE
[Discussion] ol3-cesium

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#12]
We recently decided that the map on our project should sooner or later have the possibility to not only be flat, but to look like an actual globe. I have done some research and came across [ol3-cesium](https://github.com/openlayers/ol3-cesium).

Not what I would like to discuss is if it would make sense to implement that into this project, as it is from openlayers to and also uses ol. I think it would be a nice feature, but i don't know exactly how much overweight that is going to be for someone who wont use it and therefor I'm not sure in how far it would fit into this project.

Let me know what you think and if you like the idea I'll sit to it into implementing it into this project instead of into ours directly.

**Comment by quentin-ol** [comment]
Hey @FallenRiteMonk, I didn't know about this library:  very interesting. 
It does seem fairly simple to implement as well, especially with the change I made in the dev branch. 
I will definitely give it try. Feel free to chime in if you're willing to help.
Thanks again for making me discover this library!

**Comment by FallenRiteMonk** [comment]
I have already given it a try, but I didn't even get as far as importing the library. I opened an [issue](https://github.com/openlayers/ol3-cesium/issues/426). If you have any ideas or know hot to fix it, please let me know.

**Comment by quentin-ol** [comment]
closing this for now. Please re-open if there is anything new.
