### ISSUE TITLE
bing source

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#13]
Just wanted to ask if the bing source works for you, as I'm trying to do something similar to what you are doing there with the key string.
But I always get the error: ```
error_handler.js:53Error: No provider for String! ```
and leaving it away and passing this.key to the super constructor results in an error about not being able to call this before calling the super constructor, which is totally clear.
So if it works for you, please let me know what I'm doing wrong so that i can fix it.

Thanks

**Comment by quentin-ol** [comment]
Hey,

I will look into this later this afternoon (in a few hours).
Thanks for spotting the issue and sorry that  things are not as polished as it should.
Quentin

**Comment by quentin-ol** [comment]
Quick update: found the reason why this isn't working.
Apart from the silly mistake that I made, i.e. passing the key using dependency injection, the problem stems from the way the BingMap source component is initialised: it's created before its inputs are resolved. It means that the ol.source.BingMaps instance is created without an API key, hence the issue.

I'm working on a rewrite of the source components to tackle this issue: the core idea is that the component itself is a container to the ol instance and that the ol instance is created in the ngOnInit callback.

I will push once I've checked I'm not breaking anything (including PR #15 )

**Comment by quentin-ol** [comment]
Quick update 2: the dev branch has a working solution for the BingMap source. Here is how to use it:
```
<aol-map>
  <aol-layer-tile>
    <aol-source-bingmaps [key]="'your-api-key'" [imagerySet]="'Aerial'">
    </aol-source-bingmaps>
  </aol-layer-tile>
</aol-map>
```

I'm still reviewing the changes before the merge.
@FallenRiteMonk, if by change you have time to test the dev branch as well, that'd be great.

**Comment by FallenRiteMonk** [comment]
@quentin-ol I'd like to test it for you, but could you please give me a bingMap key so I dont have to create one just for this test?

**Comment by quentin-ol** [comment]
@FallenRiteMonk I know that there is one in the Openlayers examples : 
https://github.com/openlayers/ol3/blob/master/examples/bing-maps.js

I myself would not use for any other purpose than testing (one-time) a feature related to OpenLayers as it's the property of the Openlayers project. You might want to ask them specifically about it.

**Comment by quentin-ol** [comment]
@FallenRiteMonk 
Just in case you need it :
- To generate a package (in angular2-openlayers folder)
```
npm pack
```
- To install this new package (in the folder of your project)
```
npm install </path/to/package_generated_by_previous_command>
```

**Comment by FallenRiteMonk** [comment]
@quentin-ol  LGTM

**Comment by FallenRiteMonk** [comment]
A quick question: for future contributions do you want me to continue on the dev branch or should I continue like until now on the master branch?

**Comment by quentin-ol** [comment]
I believe the dev branch should be merged into master. The only reason it exists is to test PRs without breaking everything for those who rely on the lib.

**Comment by quentin-ol** [comment]
oh, sorry! Re-reading my comment made me realise I wasn't clear!
The plan is to keep a dev branch for testing purposes. I was suggesting that we could merge the two of them now that the PR has been accepted and that its features and bugfixes have been tested. Obviously, next non-trivial changes will land in dev.
Thanks again for the PRs, much much appreciated! 👍

**Comment by FallenRiteMonk** [comment]
Ok sounds good!

No problem, happy to help, and I'm still also helping myself. Just hope to see this soon on npm!
