### ISSUE TITLE
Dynamic style components loading

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#27]
Reviewing #17 I noticed that if I dynamically add a Icon style to a style component, it doesn't get shown, since a subscription is done on ngAfterContentInit. Like so if a icon is added dynamically using ngIf for example, it will never be shown.
At the moment I can think of these solutions:
 * make it clear to the users that a style component always has to be filled with the according sub-style components on its initialization
 * make sub-style component trigger there subscription in the style component (calling some host method on ngInit)
 * remove sub-style components and implement them directly into style component using inputs

I personally would use solution two, as it seems the most reliable and logical one.
The first would be the easiest, but I thing (know from my self) that there are always users who don't read the full documentation and start modifying the example right away, which then might lead to errors that are hard to identify for them. Also not to forget the general lack of documentation at the moment.
I don't like the last because it wouldn't fit into the current style of the library and would make the style component look really ugly and messy for the users.

Let me know what you think.

**Comment by quentin-ol** [comment]
+1 for solution 2. This is actually what's implemented in 0.5.0, though it might change if consensus rises against this choice.

**Comment by quentin-ol** [comment]
Closing as solution 2 is implemented and no objection has been raised.
