### ISSUE TITLE
[FEATURE] popup

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#33]
It would be a really nice feature to have popups. I found [this library](https://github.com/walkermatt/ol3-popup) which could be used and should be easy to implement. I found it on the official size of openlayers  [Useful 3rd party libraries](http://openlayers.org/3rd-party/), so it is somehow supported by openlayers and shouldn't be bad.

Sadly I currently have other priorities to work on so if someone would have a look at it, otherwise I'll implement it once I find time for it.

**Comment by FallenRiteMonk** [comment]
Just to inform you, I started implementing this feature.

**Comment by quentinlampin** [comment]
closing this issue since the discussion is located at #36
