### ISSUE TITLE
Add dist to git

### ISSUE THREAD

**Issue by achimha** [quentin-ol/angular2-openlayers#39]
The `/dist` directory should be part of the git repository. This is good practise with Angular components as it allows using the repo directly via npm and also from applications that do not have a Typescript tool chain.

You can just add to your package.json:

"angular2-openlayers": "https://github.com/quentin-ol/angular2-openlayers"

or your own fork.

**Comment by achimha** [comment]
My change here (better to do yourself because a PR would have my path names):

https://github.com/achimha/angular2-openlayers/commit/e83eff6189211f4fc1d6f0c56d54fb2dd2c2acbe

The /aot directory is not needed, should still remain in `.gitignore`.

**Comment by quentinlampin** [comment]
PR #40 seems to address this issue
