### ISSUE TITLE
AttributionLike for sources

### ISSUE THREAD

**Issue by achimha** [quentin-ol/angular2-openlayers#43]
Each `ol.source` class has an `AttributionLike` parameter (which can be set separately). I wonder how to implement this best. Doing it as a child component would mean duplicating the attribution and when one author provides several layers, the same copyright would be rendered multiple times.

http://openlayers.org/en/latest/apidoc/ol.html#.AttributionLike

Suggestions? The best solution I've come up with is to let the library user provide the `ol.AttributionLike` directly as an input parameter to the source components. This means exposing OL3 internals.

**Comment by achimha** [comment]
A declarative approach would require defining the attribution outside the source, giving it a n Angular variable and then referencing the variable form the sources. That is probably the most Angular friendly approach.

For now I have taken another which I believe is OK as well:

```
<aol-source-xyz
  [attributions]="myAttributions"
>
</aol-source-xyz>
```

and in the component:

```
myAttributions = [
        new Attribution({
            html: '&copy;&nbsp;<a href=\"http://somebody.org\">Somebody</a>'
        })
    ];
```

The cleaner solution would be something along those lines:

```
<aol-source-attribution #myAttributions>
   &copy;&nbsp;<a href=\"http://somebody.org\">Somebody</a>
</aol-source-attribution>

<aol-source-xyz
  [attributions]="myAttributions"
>
</aol-source-xyz>
```

Alternatively, it should take an array of attribution components. Again, the main objective is to share one attribution declaration among multiple sources without having it show up multiple times so the attribution cannot be declared inside the source definition.

**Comment by quentinlampin** [comment]
I'm in favor of creating an `aol-attribution` component, _i.e_ that bundles an  [ol.Attribution](http://openlayers.org/en/latest/apidoc/ol.Attribution.html) instance, i.e. the cleaner (:)) solution!

Using transclusion (if that's still the correct name for this in Angular2), we could retrieve the HTML content and pass it to the ol.Attribution instance. It could be used like this:
```html
<aol-source-*>
 <aol-attribution>
   All maps ©
   <a href="https://www.opencyclemap.org/">OpenCycleMap</a>
 </aol-attribution>
</aol-source-*>
```
In my opinion, 
pros:
 - explicit, straight-forward
 - flexible: the component uses the transcluded content. As long as it ends up being valid HTML.
cons:
 - 1 <aol-attribution> per source instance...

Thoughts, opinions ?

**Comment by quentinlampin** [comment]
by the way, thank you @achimha for the awesome work you've done.

**Comment by achimha** [comment]
The real issue on the attribution is a use case where you have multiple sources from the same copyright holder. The modular approach means we get the same (C) message several times. I think this is both a valid and frequent use case.

Maybe we support the transclusion scenario and in addition have an `@Input()` parameter that returns the `AttributionLike` and use that when given instead of the `<ng-content>`?

**Comment by achimha** [comment]
Implemented as dicussed. We now have two options: either use the declarative fashion

```
<aol-source-*>
  <aol-attributions>
    <aol-attribution>MY WORK AND ONLY MINE</aol-attribution>
  </aol-attributions>
</aol-source-*>
```

Or pass an `ol.AttributionLike` via the `[attributions]="xyz"` property to the source directive.
