### ISSUE TITLE
Unable to remove default controlls

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#47]
Hy,

there is currently no possibility to remove the default controls added to a map or change there options, or at least I didn't find a way to do it.
I found the DefaultControlComponent, but it's inputs do not affect the component in any way! Is there some code missing or am I overseeing something.

**Comment by achimha** [comment]
Yes, I think that is a bug. The [documentation](http://openlayers.org/en/latest/apidoc/ol.Map.html) states:

> Controls initially added to the map. If not specified, ol.control.defaults() is used.

As we have a separate directive for the default components, we should explicitly set the member to an empty collection.

**Comment by achimha** [comment]
Created a PR: https://github.com/quentin-ol/angular2-openlayers/pull/49

**Comment by quentin-ol** [comment]
Thanks, nice work!
