### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#51]
This is just one of my ideas, but I think we could discuss about it.

I thought about creating a animation class with all the required inputs that then could be passes to a view in one of the following ways (we could choose one or implement even both):
 * have a default animation as input on a view, which is used used once the x and/or y input change (mainly for re centering the view)
 * have a general animation input on a view (single animation or array) which are fired on change. Not sure if there isn't a better way to achieve something like this, but currently its the only way I can think of.

I personally think the second one should be implemented for sure (maybe not exactly as described but in some way) because it would give a wide range of ways to use (also for re centering the map). The first is not really needed, but would give a easier way to recenter the map without having the create an animation every time.

I'd be pleased to create a PR for this,
so let me know what you think.

**Comment by quentin-ol** [comment]
closing this for now, please resurrect it if need be.
