### ISSUE TITLE
Double viewport issue

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#52]
Having the following map on my site:
```
<aol-map id="map">
          <aol-view [zoom]="15">
            <aol-coordinate [x]="location.gpsLong" [y]="location.gpsLat" [srid]="'EPSG:4326'"></aol-coordinate>
          </aol-view>
          <aol-control-zoom></aol-control-zoom>
          <aol-control-scaleline></aol-control-scaleline>
          <aol-control-attribution [collapsible]="false"></aol-control-attribution>
          <aol-interaction-default></aol-interaction-default>
          <aol-layer-tile>
            <aol-source-osm></aol-source-osm>
          </aol-layer-tile>
          <aol-layer-vector>
            <aol-source-vector>
              <aol-feature>
                <aol-geometry-point>
                  <aol-coordinate [x]="location.gpsLong" [y]="location.gpsLat" [srid]="'EPSG:4326'"></aol-coordinate>
                </aol-geometry-point>
                <aol-style>
                  <aol-style-icon [src]="'assets/imgs/flag.svg'" [anchor]="[0, 0]" [scale]="0.3" [anchorOrigin]="'bottom-left'" [imgSize]="[81, 81]">
                  </aol-style-icon>
                </aol-style>
              </aol-feature>
            </aol-source-vector>
          </aol-layer-vector>
        </aol-map>
```

I have the situation that upon a fresh load of the site everything is perfectly fine, only if I then navigate to a different page and then go back, my map has two view ports:
```
<aol-map>
    <div style="width: 100%; height: 100%;">
        <div class="ol-viewport" style="position: relative; overflow: hidden; width: 100%; height: 100%; touch-action: none;">
            ...
        </div>
        <div class="ol-viewport" style="position: relative; overflow: hidden; width: 100%; height: 100%; touch-action: none;">
            ...
        </div>
    </div>
    ...
</aol-map>
```

Is this a bug due to something not being destroyed correctly or am I doing something wrong?

**Comment by FallenRiteMonk** [comment]
It seems that has something to do with my location being loaded by a service. Adding ```*ngIf="location"``` to the map component solved my problem, but still I'd like to understand what is going on here, as I use the exact same structured map, with the only difference being a static center point and instead of one flag for a location, it is a list of locations.

The strange thing is that one of the viewports only contained controls (as far as I could tell they were the default controls), but removing all controls and interactions didn't change the behavior. Also setting the map center to a static point instead of the locations position didn't help.

If you have any ideas what could be going wrong let me know and I'll give it a try so that we can find a potential solution for this.

**Comment by quentin-ol** [comment]
Hey @FallenRiteMonk, any news on this ?
I'm trying to reproduce this behavior to no avail.

**Comment by FallenRiteMonk** [comment]
I'll try to reproduce it with a minimal example once I find the time for it!

**Comment by quentin-ol** [comment]
Great! Thanks!

**Comment by quentin-ol** [comment]
Is it still occuring or should we close this issue?
