### ISSUE TITLE
Attribution positioning error

### ISSUE THREAD

**Issue by FallenRiteMonk** [quentin-ol/angular2-openlayers#56]
Adding the attribution to the map results in the attribution being positioned totally wrong!

I have a router outlet with a static height of 350px (content overflow auto) and then have a route containing the following:
```
<div id="wrapper">
   <aol-map [height]="'200px'">
      ...
   </aol-map>
</div>
```

The wrapper also has a height of 200px, so the map should not be any higher than 200px, which it issn't only that if I add <aol-control-attribution ></aol-control-attribution> it results in the following:
![image](https://cloud.githubusercontent.com/assets/8779846/24194450/72770ece-0ef6-11e7-82c2-85699632db71.png)

The box represents the container of the router outlet. One can clearly see that the map has it's desired height, but the attribution is in the bottom right of the outlet corner instead of the maps corner.
The strange thing is that it is not in the corner of the wrapper (that was actually what I tried to achieve with the wrapper, otherwise it wouldn't even be needed, but without success)

**Comment by quentin-ol** [comment]
Could you provide a simple example that reproduces this?

Using chrome/firefox developers tools, could you show us the computed styles for this. I might be a css rule that is overruled. Remember that for now, we provide the `openlayer.css` independently of our components (#8) so we don't benefit from angular2 prefixing (which could prevent such behaviours).

**Comment by quentin-ol** [comment]
@FallenRiteMonk do you have news on this? I can't do much to help you as I can't reproduce it.
