### ISSUE TITLE
How does <aol-source-tilewms> works?

### ISSUE THREAD

**Issue by SemVC7** [quentin-ol/angular2-openlayers#59]
Can you please provide me an example of the aol-source-tilewms implementation?

Thanks in advance!

**Comment by billfarmakis** [comment]
No problem, using the Open Layers example for Tiled WMS https://openlayers.org/en/latest/examples/wms-tiled.html

<aol-layer-tile>
  <aol-source-tilewms [url]="'https://ahocevar.com/geoserver/wms'" [params]="{'LAYERS': 'topp:states', 'TILED': true}" [serverType]="'geoserver'"></aol-source-tilewms>
</aol-layer-tile>

**Comment by quentin-ol** [comment]
Thanks, @billfarmakis.
