### ISSUE TITLE
WMS example 

### ISSUE THREAD

**Issue by xtarx** [quentin-ol/angular2-openlayers#68]
Hello, thanks so much for the wonderful effort

I have 3 questions:

1. Can you publish the latest release to NPM as the release on NPM is (0.6.5)
2. Can you provide a WMS example
3. Do you have a map/layer switcher in plan? 

Thanks again :+1:

**Comment by quentin-ol** [comment]
npm is now up-to-date.

I'm not using WMS so I can't help you on this but Openlayers own examples usually translate quite easily to angular2-openlayers. 

Leaving this open:  if anyone reading this has an example at hand, feel free to share. This would also be a great addition to the documentation.

**Comment by xtarx** [comment]
@quentin-ol  thank you so much for the quick response, I'll give it a try and will add it to documentation :+1:

**Comment by quentin-ol** [comment]
btw, #59 might be useful.

**Comment by quentin-ol** [comment]
While I'm at reviewing open issues, is this still an issue? 
To my understanding, issue #59 provides a solution to making WMS source/tiles work.
Isn't it?

**Comment by xtarx** [comment]
Yea it is very helpful.. thanks I will close it
