### ISSUE TITLE
Move map with mouse or touch

### ISSUE THREAD

**Issue by xtarx** [quentin-ol/angular2-openlayers#69]
The map doesn't works fine, but it doesn't allow user to control it by mouse or a touch event

as seen [here  ](http://i.imgur.com/2C2vQ5N.gifv)

as the same behavior [here ](https://developers.google.com/maps/documentation/embed/guide)for example 

[GoogleMaps Pan](http://i.imgur.com/v1HLQFd.gifv)

Code used:
```
<aol-map>
      <aol-view [zoom]="5">
        <aol-coordinate [x]="5" [y]="45" [srid]="'EPSG:4326'"></aol-coordinate>
      </aol-view>
      <aol-interaction-pinchzoom></aol-interaction-pinchzoom><aol-control-zoom></aol-control-zoom>
      <aol-control-fullscreen></aol-control-fullscreen>

      <aol-layer-tile>
        <aol-source-osm></aol-source-osm>
      </aol-layer-tile>
    </aol-map>
```

is there any control I need to add to have the behavior specified above?

**Comment by quentin-ol** [comment]
Could you provide more information on this, i.e. what is the behaviour you're observing, what was expected and if possible a minimal example that shows the issue.

I have an angular app that I'm using on my smartphone and it works as expected: pinches zoom the map, strokes pan the map, etc.

**Comment by xtarx** [comment]
@quentin-ol  thank you for your response,I have updated the question. Hope it is more clear now :)

**Comment by lautarobock** [comment]
The same is happen to me. I'm trying with your own example [here](https://github.com/quentin-ol/angular2-openlayers/tree/master/example)

package.json
```
"dependencies": {
    "@angular/animations": "^4.1.3",
    "openlayers": "4.0.x || 4.1.x"
  },
  "devDependencies": {
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-server": "^4.1.3",
    "@types/jasmine": "^2.5.38",
    "@types/openlayers": "4.1.0",
    "@types/selenium-webdriver": "^3.0.4",
    "codelyzer": "3.0.1",
    "rxjs": "5.4.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "zone.js": "0.8.11"
  },
```

**Comment by quentin-ol** [comment]
The example is the simplest map you could get, i.e no interaction and a simple feature (for a "find us" page). If you want to add interactions to the maps and unless you have specific needs, you should add an aol-interaction-default to the map, _e.g._ (adding interactions to example):
```
<aol-map [width]="'100%'" [height]="'100%'">
	<aol-interaction-default></aol-interaction-default>
	<aol-view [zoom]="zoom">
		<aol-coordinate [x]="5" [y]="45" [srid]="'EPSG:4326'"></aol-coordinate>
	</aol-view>
	<aol-layer-tile [opacity]="opacity">
    <aol-source-osm></aol-source-osm>
	</aol-layer-tile>
	<aol-layer-vector [opacity]="opacity">
		<aol-source-vector>
			<aol-feature>
				<aol-geometry-point>
					<aol-coordinate [x]="5" [y]="45" [srid]="'EPSG:4326'"></aol-coordinate>
				</aol-geometry-point>
				<aol-style>
					<aol-style-circle [radius]="10">
						<aol-style-stroke [color]="'black'" [width]="width"></aol-style-stroke>
						<aol-style-fill [color]="'green'"></aol-style-fill>
					</aol-style-circle>
				</aol-style>
			</aol-feature>
			<aol-feature>
				<aol-geometry-point>
					<aol-coordinate [x]="5.1" [y]="45.1" [srid]="'EPSG:4326'"></aol-coordinate>
				</aol-geometry-point>
				<aol-style>
	        <aol-style-icon
	          [src]="'assets/marker.png'"
	          [anchor]="[0.5, 1]"
	          [anchorXUnits]="'fraction'" [anchorYUnits]="'fraction'"
	          [scale]="0.1"
	          [anchorOrigin]="'top-left'">
	        </aol-style-icon>
	      </aol-style>
	    </aol-feature>
		</aol-source-vector>
	</aol-layer-vector>
</aol-map>
```

**Comment by xtarx** [comment]
Thanks that was the missing piece  `	<aol-interaction-default></aol-interaction-default>
`

**Comment by lautarobock** [comment]
it could be possible that event `moveend` do not work?

**Comment by lautarobock** [comment]
Searching into the sourcecode I found that the event name is `onMoveEnd`,
