### ISSUE TITLE
Unable to install npm package

### ISSUE THREAD

**Issue by giridharkl** [quentin-ol/angular2-openlayers#79]
C:\MProjects\MGMT\modules\taskmgmt>npm install angular2-openlayers --save
npm ERR! path C:\MProjects\MGMT\modules\taskmgmt\https:\registry.npmjs.org\tapable\-\tapable-0.2.6.tgz
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall stat
npm ERR! enoent ENOENT: no such file or directory, stat 'C:\MProjects\MGMT\modules\taskmgmt\https:\registry.npmjs.org\tapable\-\tapable-0.2.6.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxyyyy\AppData\Roaming\npm-cache\_logs\2017-07-12T07_07_21_181Z-debug.log

**Comment by quentin-ol** [comment]
The error complains about tapable. Nothing to do with angular2-openlayers. Closing.
