### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by giridharkl** [quentin-ol/angular2-openlayers#81]
<project_folder>/node_modules/angular2-openlayers/dist/components/controls/attribution.component.d.ts (1,1): Cannot find type definition file for 'openlayers'.

Please help!

After installing @types/openlayers it compiles!
Thanks

**Comment by rbrcurtis** [comment]
I'm getting the same thing.

**Comment by quentin-ol** [comment]
Could you provide how you get this, i.e. what steps are needed to reproduce this error.
Thanks,

Quentin

**Comment by pieterdb4477** [comment]
I have the same problem. Reproducing it can be done with a new angular project generated by angular-cli, installing OL with npm and then ng serve.

Angular cli version: 1.2.3
npm version: 5.3.0
node version: 6.10.2
angular version: ^4.0.0

**Comment by quentin-ol** [comment]
Solution #58 merged in https://github.com/quentin-ol/angular2-openlayers/commit/39b4e83a56558a4545741b984fcd31f9524e0674.

#89 added a Travis build that ensures the example is working. Thanks again to @Neonox31 and his pals for this.

**Comment by Neonox31** [comment]
Anytime :) Glad it helped
