### ISSUE TITLE
Creation of a gitter chat

### ISSUE THREAD

**Issue by davinkevin** [quentin-ol/angular2-openlayers#90]
Only the owner of the project can create the gitter chat we talk about earlier today.

You have to join gitter at the following URL : https://gitter.im (with your github credentials)

And to create a room in it with the button `Add a room`
![image](https://user-images.githubusercontent.com/1970922/29120580-3eb28b94-7d0b-11e7-94ce-f79d2534e1bc.png)

Then choose the angular2-openlayers project. A PR is made by default on the README.md to add the gitter badge in the readme.
![image](https://user-images.githubusercontent.com/1970922/29120604-5147eab0-7d0b-11e7-8ff7-652de5c71c7b.png)

After that, we will have a simple but powerfull chat dedicated to the project

Thanks 😄 

/cc @Neonox31 @Yakoust @Yann29

**Comment by quentin-ol** [comment]
[https://gitter.im/angular2-openlayers](https://gitter.im/angular2-openlayers) is now live!
Badge & Getting Help section now available in `README.md` (https://github.com/quentin-ol/angular2-openlayers/commit/4484aefec026c55ddb1247d071a9ce2b17e428be).
